#!/usr/bin/env bash
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  AI Video Platform - Setup Script${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Check prerequisites
check_command() {
    if ! command -v "$1" &> /dev/null; then
        echo -e "${RED}✗ $1 is not installed${NC}"
        return 1
    else
        echo -e "${GREEN}✓ $1 found${NC}"
        return 0
    fi
}

echo "Checking prerequisites..."
check_command docker || { echo "Please install Docker: https://docs.docker.com/get-docker/"; exit 1; }
check_command docker-compose || check_command "docker compose" || { echo "Please install Docker Compose"; exit 1; }
check_command curl || { echo "Please install curl"; exit 1; }

echo ""

# Create .env if it doesn't exist
if [ -f ".env" ]; then
    echo -e "${YELLOW}.env already exists. Skipping configuration.${NC}"
    read -p "Do you want to reconfigure? (y/N): " reconfigure
    if [[ ! "$reconfigure" =~ ^[Yy]$ ]]; then
        echo "Using existing .env"
    else
        rm .env
    fi
fi

if [ ! -f ".env" ]; then
    echo -e "${BLUE}Let's configure your environment...${NC}"
    echo ""

    # Security keys
    echo -e "${YELLOW}Generating secure random keys...${NC}"
    SECRET_KEY=$(openssl rand -hex 32)
    NEXTAUTH_SECRET=$(openssl rand -hex 32)

    # AI Provider
    echo ""
    echo -e "${BLUE}AI Provider Configuration${NC}"
    echo "You need at least one AI provider API key."
    echo "Get one free at: https://replicate.com/account/api-tokens"
    echo ""

    read -p "Enter Replicate API Token (press Enter to skip): " REPLICATE_TOKEN
    read -p "Enter Runway API Key (press Enter to skip): " RUNWAY_KEY

    if [ -z "$REPLICATE_TOKEN" ] && [ -z "$RUNWAY_KEY" ]; then
        echo -e "${RED}ERROR: You must provide at least one AI provider API key.${NC}"
        exit 1
    fi

    # Storage
    echo ""
    echo -e "${BLUE}Storage Configuration (S3-compatible)${NC}"
    echo "Options: AWS S3, Cloudflare R2, MinIO, Wasabi, etc."
    echo ""

    read -p "S3 Access Key ID: " S3_KEY
    read -p "S3 Secret Access Key: " S3_SECRET
    read -p "S3 Bucket Name [ai-video-platform]: " S3_BUCKET
    S3_BUCKET=${S3_BUCKET:-ai-video-platform}
    read -p "S3 Endpoint [https://s3.us-east-1.amazonaws.com]: " S3_ENDPOINT
    S3_ENDPOINT=${S3_ENDPOINT:-https://s3.us-east-1.amazonaws.com}
    read -p "S3 Region [us-east-1]: " S3_REGION
    S3_REGION=${S3_REGION:-us-east-1}
    read -p "S3 Public URL (CDN, optional): " S3_PUBLIC

    if [ -z "$S3_KEY" ] || [ -z "$S3_SECRET" ]; then
        echo -e "${RED}ERROR: S3 credentials are required for video storage.${NC}"
        exit 1
    fi

    # OAuth (optional)
    echo ""
    read -p "Configure Google OAuth? (y/N): " setup_oauth
    GOOGLE_ID=""
    GOOGLE_SECRET=""
    if [[ "$setup_oauth" =~ ^[Yy]$ ]]; then
        echo "Get credentials at: https://console.cloud.google.com/apis/credentials"
        read -p "Google Client ID: " GOOGLE_ID
        read -p "Google Client Secret: " GOOGLE_SECRET
    fi

    # Stripe (optional)
    echo ""
    read -p "Configure Stripe payments? (y/N): " setup_stripe
    STRIPE_KEY=""
    STRIPE_WEBHOOK=""
    STRIPE_PRICE=""
    if [[ "$setup_stripe" =~ ^[Yy]$ ]]; then
        read -p "Stripe Secret Key (sk_test_...): " STRIPE_KEY
        read -p "Stripe Webhook Secret (whsec_...): " STRIPE_WEBHOOK
        read -p "Stripe Price ID for credits (price_...): " STRIPE_PRICE
    fi

    # Build .env file
    cat > .env <<EOF
# Auto-generated by setup.sh on $(date)

# Database
DATABASE_URL=postgresql+asyncpg://avp:avp_secret@postgres:5432/aivideo
POSTGRES_USER=avp
POSTGRES_PASSWORD=avp_secret
POSTGRES_DB=aivideo

# Redis
REDIS_URL=redis://redis:6379/0
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/0

# Security
SECRET_KEY=${SECRET_KEY}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

# AI Providers
REPLICATE_API_TOKEN=${REPLICATE_TOKEN}
RUNWAY_API_KEY=${RUNWAY_KEY}
DEFAULT_AI_PROVIDER=replicate

# Storage
AWS_ACCESS_KEY_ID=${S3_KEY}
AWS_SECRET_ACCESS_KEY=${S3_SECRET}
S3_BUCKET=${S3_BUCKET}
S3_ENDPOINT=${S3_ENDPOINT}
S3_REGION=${S3_REGION}
S3_PUBLIC_URL=${S3_PUBLIC}

# Application
FRONTEND_URL=http://localhost:3000
NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXTAUTH_URL=http://localhost:3000

# OAuth
GOOGLE_CLIENT_ID=${GOOGLE_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_SECRET}

# Stripe
STRIPE_SECRET_KEY=${STRIPE_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK}
STRIPE_PRICE_ID_CREDITS=${STRIPE_PRICE}

# Business Logic
CREDITS_PER_GENERATION=10
DEFAULT_FREE_CREDITS=50
MAX_VIDEO_DURATION_SECONDS=5
EOF

    echo ""
    echo -e "${GREEN}✓ .env created successfully${NC}"
fi

# Validate API keys
echo ""
echo -e "${BLUE}Validating API keys...${NC}"

if [ -n "$REPLICATE_API_TOKEN" ] || grep -q "REPLICATE_API_TOKEN=" .env && ! grep -q "REPLICATE_API_TOKEN=$" .env; then
    REPLICATE_TOKEN=$(grep "REPLICATE_API_TOKEN=" .env | cut -d'=' -f2)
    if [ -n "$REPLICATE_TOKEN" ]; then
        HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Token ${REPLICATE_TOKEN}" https://api.replicate.com/v1/models || true)
        if [ "$HTTP_STATUS" = "200" ]; then
            echo -e "${GREEN}✓ Replicate API key is valid${NC}"
        else
            echo -e "${YELLOW}⚠ Replicate API key may be invalid (HTTP ${HTTP_STATUS})${NC}"
        fi
    fi
fi

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Starting AI Video Platform...${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Pull and build
docker-compose pull
docker-compose up --build -d

echo ""
echo -e "${BLUE}Waiting for services to start...${NC}"
sleep 10

# Health checks
echo ""
echo -e "${BLUE}Running health checks...${NC}"

for i in {1..30}; do
    BACKEND_HEALTH=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health || echo "000")
    if [ "$BACKEND_HEALTH" = "200" ]; then
        echo -e "${GREEN}✓ Backend is healthy${NC}"
        break
    fi
    echo -n "."
    sleep 2
done

if [ "$BACKEND_HEALTH" != "200" ]; then
    echo -e "${RED}✗ Backend failed to start. Check logs: docker-compose logs backend${NC}"
    exit 1
fi

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  🎉 AI Video Platform is running!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "  ${BLUE}Frontend:${NC}  http://localhost:3000"
echo -e "  ${BLUE}API:${NC}       http://localhost:8000"
echo -e "  ${BLUE}API Docs:${NC}  http://localhost:8000/docs"
echo ""
echo -e "  ${YELLOW}Next steps:${NC}"
echo -e "  1. Open http://localhost:3000/register"
echo -e "  2. Create an account (50 free credits)"
echo -e "  3. Go to Generate and create your first video"
echo ""
echo -e "  ${YELLOW}Useful commands:${NC}"
echo -e "  make logs     - View all logs"
echo -e "  make stop     - Stop all services"
echo -e "  make reset    - Reset all data"
echo ""
